name: smart_pantry
description: "A smart waste optimization mobile application."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Local Offline Database
  sqflite: ^2.3.3+1
  path: ^1.9.0

  # State Management (The App Brain)
  flutter_riverpod: ^2.5.0

  # AI Engine
  google_generative_ai: ^0.4.0

  # Text Scanner Engine (OCR)
  google_mlkit_text_recognition: ^0.13.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
